import jsPDF from 'jspdf';
import { CompanyProfile, Quotation } from './storage';

/**
 * Share a PDF file using the Web Share API
 * @param pdfBlob - The PDF blob to share
 * @param fileName - The name of the file to share
 * @returns Promise that resolves when sharing is complete or rejects if sharing fails
 */
export const shareQuotation = async (pdfBlob: Blob, fileName: string): Promise<void> => {
  // Check if Web Share API is supported
  if (!navigator.share) {
    throw new Error('Web Share API is not supported in this browser');
  }

  // Check if the browser can share files
  if (!navigator.canShare) {
    throw new Error('File sharing is not supported in this browser');
  }

  // Create a File object from the Blob
  const file = new File([pdfBlob], fileName, { type: 'application/pdf' });

  // Check if we can share this file
  if (!navigator.canShare({ files: [file] })) {
    throw new Error('This file type cannot be shared');
  }

  try {
    await navigator.share({
      files: [file],
      title: 'Quotation PDF',
      text: 'Please find the quotation attached.',
    });
  } catch (error: any) {
    // User cancelled the share or an error occurred
    if (error.name === 'AbortError') {
      throw new Error('Share cancelled');
    }
    throw error;
  }
};

export const generatePDF = (
  quotation: Quotation,
  companyProfile: CompanyProfile
): jsPDF => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  let yPos = 20;
  let pageNum = 1;

  // --- Watermark ---
  const addWatermark = () => {
    if (companyProfile.logo) {
      try {
        doc.saveGraphicsState();
        doc.setGState({ opacity: 0.1 });
        const watermarkSize = 80;
        doc.addImage(
          companyProfile.logo,
          'PNG',
          (pageWidth - watermarkSize) / 2,
          (pageHeight - watermarkSize) / 2,
          watermarkSize,
          watermarkSize
        );
        doc.restoreGraphicsState();
      } catch (error) {
        console.error('Error adding watermark:', error);
      }
    }
  };

  // --- Footer ---
  const addFooter = (pageNum: number) => {
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated on: ${new Date().toLocaleDateString('en-GB')}`, 20, pageHeight - 15);
    doc.text(
      'This page is generated by software developed by Muzammil',
      pageWidth / 2,
      pageHeight - 15,
      { align: 'center' }
    );
    doc.text(`Page ${pageNum}`, pageWidth - 20, pageHeight - 15, { align: 'right' });
  };

  addWatermark();

  // --- Company Logo ---
  if (companyProfile.logo) {
    try {
      doc.addImage(companyProfile.logo, 'PNG', pageWidth / 2 - 15, yPos, 30, 30);
      yPos += 35;
    } catch (error) {
      console.error('Error adding logo:', error);
    }
  }

  // --- Company Info ---
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(33, 150, 243); // Use reference color
  doc.text(companyProfile.companyName, pageWidth / 2, yPos, { align: 'center' });
  yPos += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);
  doc.text(`Email: ${companyProfile.email}`, pageWidth / 2, yPos, { align: 'center' });
  yPos += 5;
  doc.text(`Contact: ${companyProfile.contactNumber}`, pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  // --- Quotation Title ---
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('QUOTATION', pageWidth / 2, yPos, { align: 'center' });
  yPos += 10;

  // --- Quotation & Client Details ---
  doc.setFontSize(10);

  // Client details
  doc.setFont('helvetica', 'bold');
  doc.text('Client Name:', 20, yPos);
  doc.setFont('helvetica', 'normal');
  doc.text(quotation.clientName, 50, yPos);

  doc.setFont('helvetica', 'bold');
  doc.text('Quotation #:', pageWidth - 80, yPos);
  doc.setFont('helvetica', 'normal');
  doc.text(quotation.quotationNumber, pageWidth - 20, yPos, { align: 'right' });
  yPos += 5;

  doc.setFont('helvetica', 'bold');
  doc.text('Contact:', 20, yPos);
  doc.setFont('helvetica', 'normal');
  doc.text(quotation.clientContact, 50, yPos);

  doc.setFont('helvetica', 'bold');
  doc.text('Date:', pageWidth - 80, yPos);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date(quotation.date).toLocaleDateString(), pageWidth - 20, yPos, { align: 'right' });
  yPos += 5;

  doc.setFont('helvetica', 'bold');
  doc.text('Email:', 20, yPos);
  doc.setFont('helvetica', 'normal');
  const clientEmailText = doc.splitTextToSize(quotation.clientEmail, 80);
  doc.text(clientEmailText, 50, yPos);
  yPos += 12;

  // --- Items Table ---
  const tableStartY = yPos;
  const colWidths = [15, 80, 25, 30, 30];
  const headers = ['S.No', 'Description', 'Qty', 'Unit Price', 'Total'];

  doc.setFillColor(203 * 2.55, 0.89 * 255, 0.45 * 255); // Reference table color
  doc.rect(20, yPos, pageWidth - 40, 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');

  let xPos = 20;
  headers.forEach((header, i) => {
    doc.text(header, xPos + 2, yPos + 5);
    xPos += colWidths[i];
  });
  yPos += 8;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  quotation.items.forEach((item, index) => {
    if (yPos > pageHeight - 40) {
      addFooter(pageNum);
      doc.addPage();
      addWatermark();
      pageNum++;
      yPos = 20;
    }
    xPos = 20;
    doc.text(String(index + 1), xPos + 2, yPos + 5);
    xPos += colWidths[0];

    const descLines = doc.splitTextToSize(item.description, colWidths[1] - 4);
    doc.text(descLines, xPos + 2, yPos + 5);
    xPos += colWidths[1];

    doc.text(String(item.quantity), xPos + 2, yPos + 5);
    xPos += colWidths[2];

    doc.text(`PKR ${item.unitPrice.toFixed(2)}`, xPos + 2, yPos + 5);
    xPos += colWidths[3];

    doc.text(`PKR ${item.total.toFixed(2)}`, xPos + 2, yPos + 5);
    yPos += Math.max(8, descLines.length * 5);
  });

  yPos += 5;

  // --- Summary ---
  const summaryX = pageWidth - 80;
  doc.setFont('helvetica', 'normal');
  doc.text('Subtotal:', summaryX, yPos);
  doc.text(`PKR ${quotation.subtotal.toFixed(2)}`, pageWidth - 20, yPos, { align: 'right' });
  yPos += 6;

  if (quotation.taxPercent > 0) {
    doc.text(`Tax (${quotation.taxPercent}%):`, summaryX, yPos);
    const taxAmount = (quotation.subtotal * quotation.taxPercent) / 100;
    doc.text(`PKR ${taxAmount.toFixed(2)}`, pageWidth - 20, yPos, { align: 'right' });
    yPos += 6;
  }

  if (quotation.discountPercent > 0) {
    doc.text(`Discount (${quotation.discountPercent}%):`, summaryX, yPos);
    const discountAmount = (quotation.subtotal * quotation.discountPercent) / 100;
    doc.text(`-PKR ${discountAmount.toFixed(2)}`, pageWidth - 20, yPos, { align: 'right' });
    yPos += 6;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Grand Total:', summaryX, yPos);
  doc.text(`PKR ${quotation.grandTotal.toFixed(2)}`, pageWidth - 20, yPos, { align: 'right' });
  yPos += 15;

  // --- Terms & Conditions ---
  if (quotation.termsAndConditions) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Terms & Conditions:', 20, yPos);
    yPos += 6;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    const termsLines = doc.splitTextToSize(quotation.termsAndConditions, pageWidth - 40);
    termsLines.forEach(line => {
      if (yPos > pageHeight - 40) {
        addFooter(pageNum);
        doc.addPage();
        addWatermark();
        pageNum++;
        yPos = 20;
      }
      doc.text(line, 20, yPos);
      yPos += 5;
    });
  }

  // --- Thank You Note ---
  if (yPos > pageHeight - 35) {
    addFooter(pageNum);
    doc.addPage();
    addWatermark();
    pageNum++;
    yPos = 20;
  }
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.text('Thank you for your business!', pageWidth / 2, yPos, { align: 'center' });

  // --- Footer ---
  addFooter(pageNum);

  return doc;
};
